# Generated by Django 5.2 on 2025-05-13 14:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_eventregistration_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('sponsor', models.CharField(choices=[('sponsor1', 'Sponsor 1'), ('sponsor2', 'Sponsor 2'), ('sponsor3', 'Sponsor 3'), ('sponsor4', 'Sponsor 4')], max_length=50)),
                ('merch_type', models.CharField(choices=[('sweatshirt', 'Sweatshirt'), ('cap', 'Cap'), ('hoodie', 'Hoodie'), ('socks', 'Socks'), ('pants', 'Pants'), ('mug', 'Mug')], max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
            ],
        ),
    ]
